server:
  port: 9090

spring:
  profiles:
    active: dev
    include:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  jackson:
    serialization.indent_output: true