kafka:
  bootstrapAddress: localhost:9092
  groupId: priceTest
  topic: priceFeedTest

price:
  commission:
    rate:
       bid : -0.1
       ask : 0.1

spring:
  redis:
    host: localhost
    port: 6379

application:
  locale: en-UK