kafka:
  bootstrapAddress: localhost:9092
  groupId: price
  topic: priceFeed

price:
  commission:
    rate:
       bid : -0.1
       ask : 0.1

spring:
  redis:
    host: localhost
    port: 6379

  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

application:
        locale: en-UK